# Generated by Django 4.1.5 on 2023-01-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.DateTimeField(null=True),
        ),
    ]
