# Generated by Django 4.1.5 on 2023-01-05 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
    ]
