# Generated by Django 4.1.5 on 2023-01-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
